export const MOCK_ADITIVOS = {
  aditivos: {
    aditivos: {
      sulfitos: {
        nombre: "Sulfitos",
        tipo: "conservante",
        estado: "mezcla",
        histamina: 3,
        confianza: "alta",
        notas:
          "Grupo con señal más fuerte: pseudoalergia, broncoespasmo en personas susceptibles y datos de degranulación/liberación de histamina.",
        alias: ["E220", "E221", "E222", "E223", "E224", "E226", "E227", "E228"],
      },

      dioxido_de_azufre: {
        nombre: "Dióxido de azufre",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E220"],
      },
      sulfito_sodico: {
        nombre: "Sulfito sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E221"],
      },
      bisulfito_sodico: {
        nombre: "Bisulfito sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E222"],
      },
      metabisulfito_sodico: {
        nombre: "Metabisulfito sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E223"],
      },
      metabisulfito_potasico: {
        nombre: "Metabisulfito potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E224"],
      },
      sulfito_calcico: {
        nombre: "Sulfito cálcico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E226"],
      },
      bisulfito_calcico: {
        nombre: "Bisulfito cálcico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E227"],
      },
      bisulfito_potasico: {
        nombre: "Bisulfito potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E228"],
      },

      benzoatos: {
        nombre: "Benzoatos",
        tipo: "conservante",
        estado: "mezcla",
        histamina: 2,
        confianza: "media",
        notas:
          "Cautela relevante en subgrupos: urticaria/angioedema minoritaria y señal de liberación de histamina en mucosa gástrica humana.",
        alias: ["E210", "E211", "E212", "E213"],
      },
      acido_benzoico: {
        nombre: "Ácido benzoico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 2,
        confianza: "media",
        alias: ["E210"],
      },
      benzoato_sodico: {
        nombre: "Benzoato sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 2,
        confianza: "media",
        alias: ["E211"],
      },
      benzoato_potasico: {
        nombre: "Benzoato potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 2,
        confianza: "media",
        alias: ["E212"],
      },
      benzoato_calcico: {
        nombre: "Benzoato cálcico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 2,
        confianza: "media",
        alias: ["E213"],
      },

      bha: {
        nombre: "BHA",
        tipo: "antioxidante",
        estado: "procesado",
        histamina: 2,
        confianza: "media_baja",
        notas:
          "Señal no tan fuerte como sulfitos, pero con exacerbación de urticaria descrita y prudencia razonable en perfil sensible.",
        alias: ["E320"],
      },
      bht: {
        nombre: "BHT",
        tipo: "antioxidante",
        estado: "procesado",
        histamina: 2,
        confianza: "media_baja",
        notas:
          "Modelo animal con aumento de degranulación mastocitaria; tratar como cautela relevante en perfil histamínico sensible.",
        alias: ["E321"],
      },

      glutamato_monosodico: {
        nombre: "Glutamato monosódico",
        tipo: "potenciador",
        estado: "procesado",
        histamina: 1,
        confianza: "media_baja",
        alias: ["E621", "MSG"],
      },
      glutamatos: {
        nombre: "Glutamatos",
        tipo: "potenciador",
        estado: "mezcla",
        histamina: 1,
        confianza: "media_baja",
        alias: ["E620", "E621", "E622", "E623", "E624", "E625"],
      },

      nitritos_nitratos: {
        nombre: "Nitritos y nitratos",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        notas:
          "Cautela provisional: la preocupación principal no es histamina y algunos modelos alimentarios reducen aminas, pero hay señal aislada.",
        alias: ["E249", "E250", "E251", "E252"],
      },
      nitrito_potasico: {
        nombre: "Nitrito potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E249"],
      },
      nitrito_sodico: {
        nombre: "Nitrito sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E250"],
      },
      nitrato_sodico: {
        nombre: "Nitrato sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E251"],
      },
      nitrato_potasico: {
        nombre: "Nitrato potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E252"],
      },

      sorbatos: {
        nombre: "Sorbatos",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        notas:
          "Baja señal sistémica; pueden inhibir formación bacteriana de histamina. E203 queda como código legado fuera de la UE.",
        alias: ["E200", "E202", "E203"],
      },
      acido_sorbico: {
        nombre: "Ácido sórbico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E200"],
      },
      sorbato_potasico: {
        nombre: "Sorbato potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E202"],
      },
      sorbato_calcico: {
        nombre: "Sorbato cálcico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        notas: "Código legado: retirado en la UE por datos genotóxicos insuficientes, no por señal histamínica fuerte.",
        alias: ["E203"],
      },

      acido_ascorbico: {
        nombre: "Ácido ascórbico",
        tipo: "antioxidante",
        estado: "procesado",
        histamina: 0,
        confianza: "alta",
        alias: ["E300", "Vitamina C"],
      },
      ascorbato_sodico: {
        nombre: "Ascorbato sódico",
        tipo: "antioxidante",
        estado: "procesado",
        histamina: 0,
        confianza: "alta",
        alias: ["E301"],
      },
      ascorbato_calcico: {
        nombre: "Ascorbato cálcico",
        tipo: "antioxidante",
        estado: "procesado",
        histamina: 0,
        confianza: "alta",
        alias: ["E302"],
      },

      propionatos: {
        nombre: "Propionatos",
        tipo: "conservante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E280", "E281", "E282", "E283"],
      },
      acido_propionico: {
        nombre: "Ácido propiónico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E280"],
      },
      propionato_sodico: {
        nombre: "Propionato sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E281"],
      },
      propionato_calcico: {
        nombre: "Propionato cálcico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E282"],
      },

      edta_calcico_disodico: {
        nombre: "EDTA cálcico disódico",
        tipo: "secuestrante",
        estado: "procesado",
        histamina: 0,
        confianza: "baja",
        notas:
          "Riesgo histamínico alimentario provisionalmente bajo; evidencia insuficiente para HIT/DAO.",
        alias: ["E385"],
      },

      parabenos_alimentarios: {
        nombre: "Parabenos alimentarios",
        tipo: "conservante",
        estado: "mezcla",
        histamina: 1,
        confianza: "baja",
        notas:
          "Señal clínica rara y sin evidencia sólida específica de HIT/DAO; mantener como cautela leve.",
        alias: ["E214", "E215", "E218", "E219"],
      },
      etil_parahidroxibenzoato: {
        nombre: "Etil p-hidroxibenzoato",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E214"],
      },
      sodio_etilparabeno: {
        nombre: "Sodio etilparabeno",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E215"],
      },
      metil_parahidroxibenzoato: {
        nombre: "Metil p-hidroxibenzoato",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E218"],
      },
      sodio_metilparabeno: {
        nombre: "Sodio metilparabeno",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E219"],
      },

      carragenanos: {
        nombre: "Carragenanos",
        tipo: "gelificante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        notas:
          "Riesgo indirecto bajo por posible inflamación intestinal/microbiota; no liberador histamínico directo convincente.",
        alias: ["E407", "E407a", "Carragenano", "Alga Eucheuma procesada"],
      },
      alginatos: {
        nombre: "Alginatos",
        tipo: "gelificante",
        estado: "mezcla",
        histamina: 0,
        confianza: "media",
        notas:
          "Señal preclínica compatible con inhibición de liberación de histamina; permitir por defecto.",
        alias: ["E400", "E401", "E402", "E403", "E404", "E405"],
      },
      acido_alginico: {
        nombre: "Ácido algínico",
        tipo: "gelificante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E400"],
      },
      pectina: {
        nombre: "Pectina",
        tipo: "gelificante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        notas:
          "Datos preclínicos favorables sobre degranulación/histamina; sin señal práctica de riesgo.",
        alias: ["E440"],
      },
      agar: {
        nombre: "Agar",
        tipo: "gelificante",
        estado: "procesado",
        histamina: 0,
        confianza: "muy_baja",
        alias: ["E406"],
      },
      goma_guar: {
        nombre: "Goma guar",
        tipo: "gelificante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        notas:
          "Riesgo indirecto bajo; la señal descrita es más de alergia clásica/ocupacional que de HIT.",
        alias: ["E412", "Guar gum"],
      },
      goma_xantana: {
        nombre: "Goma xantana",
        tipo: "gelificante",
        estado: "procesado",
        histamina: 0,
        confianza: "muy_baja",
        alias: ["E415", "Xanthan gum"],
      },
      goma_garrofin: {
        nombre: "Goma garrofín",
        tipo: "gelificante",
        estado: "procesado",
        histamina: 0,
        confianza: "muy_baja",
        alias: ["E410", "Locust bean gum", "Carob gum"],
      },

      aspartamo: {
        nombre: "Aspartamo",
        tipo: "edulcorante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        notas:
          "No liberador en estudios directos revisados; sin más urticaria/angioedema que placebo en ensayo doble ciego.",
        alias: ["E951", "Aspartame"],
      },
      acesulfamo_k: {
        nombre: "Acesulfamo K",
        tipo: "edulcorante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        notas:
          "Cautela indirecta por microbiota/inflamación en modelos preclínicos; sin evidencia directa de aumento de histamina o bloqueo DAO.",
        alias: ["E950", "Acesulfame potassium"],
      },
      sucralosa: {
        nombre: "Sucralosa",
        tipo: "edulcorante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        notas:
          "Cautela indirecta por disbiosis/inflamación preclínica; no hay evidencia directa de HIT/DAO.",
        alias: ["E955", "Sucralose"],
      },
      sacarina: {
        nombre: "Sacarina",
        tipo: "edulcorante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        notas:
          "Evidencia mixta sobre microbiota; tratar como cautela leve, no como liberador demostrado.",
        alias: ["E954", "Saccharins"],
      },
      ciclamatos: {
        nombre: "Ciclamatos",
        tipo: "edulcorante",
        estado: "procesado",
        histamina: 0,
        confianza: "muy_baja",
        alias: ["E952", "Cyclamates"],
      },
      glucosidos_de_esteviol: {
        nombre: "Glucósidos de esteviol",
        tipo: "edulcorante",
        estado: "procesado",
        histamina: 0,
        confianza: "baja",
        alias: ["E960", "Steviol glycosides"],
      },
      polioles_comunes: {
        nombre: "Polioles comunes",
        tipo: "edulcorante",
        estado: "mezcla",
        histamina: 0,
        confianza: "media",
        notas:
          "No contienen histamina; el problema típico es digestivo/osmótico, no histamínico.",
        alias: ["E420", "E967", "E968", "Sorbitol", "Xilitol", "Eritritol"],
      },
      sorbitol: {
        nombre: "Sorbitol",
        tipo: "edulcorante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E420"],
      },
      xilitol: {
        nombre: "Xilitol",
        tipo: "edulcorante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E967"],
      },
      eritritol: {
        nombre: "Eritritol",
        tipo: "edulcorante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E968"],
      },
    },
  },
};
