export const MOCK_ADITIVOS = {
  aditivos: {
    aditivos: {
      sulfitos: {
        nombre: "Sulfitos",
        tipo: "conservante",
        estado: "mezcla",
        histamina: 3,
        confianza: "alta",
        notas:
          "Grupo con mejor señal de riesgo en personas sensibles a histamina.",
        alias: ["E220", "E221", "E222", "E223", "E224", "E226", "E227", "E228"],
      },

      dioxido_de_azufre: {
        nombre: "Dióxido de azufre",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E220"],
      },
      sulfito_sodico: {
        nombre: "Sulfito sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E221"],
      },
      bisulfito_sodico: {
        nombre: "Bisulfito sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E222"],
      },
      metabisulfito_sodico: {
        nombre: "Metabisulfito sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E223"],
      },
      metabisulfito_potasico: {
        nombre: "Metabisulfito potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 3,
        confianza: "alta",
        alias: ["E224"],
      },

      benzoatos: {
        nombre: "Benzoatos",
        tipo: "conservante",
        estado: "mezcla",
        histamina: 2,
        confianza: "media",
        notas:
          "Señal relevante en subgrupos sensibles; mejor evitar por defecto.",
        alias: ["E210", "E211", "E212", "E213"],
      },
      acido_benzoico: {
        nombre: "Ácido benzoico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 2,
        confianza: "media",
        alias: ["E210"],
      },
      benzoato_sodico: {
        nombre: "Benzoato sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 2,
        confianza: "media",
        alias: ["E211"],
      },
      benzoato_potasico: {
        nombre: "Benzoato potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 2,
        confianza: "media",
        alias: ["E212"],
      },
      benzoato_calcico: {
        nombre: "Benzoato cálcico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 2,
        confianza: "media",
        alias: ["E213"],
      },

      bha: {
        nombre: "BHA",
        tipo: "antioxidante",
        estado: "procesado",
        histamina: 2,
        confianza: "media_baja",
        alias: ["E320"],
      },
      bht: {
        nombre: "BHT",
        tipo: "antioxidante",
        estado: "procesado",
        histamina: 2,
        confianza: "media_baja",
        alias: ["E321"],
      },

      glutamato_monosodico: {
        nombre: "Glutamato monosódico",
        tipo: "potenciador",
        estado: "procesado",
        histamina: 1,
        confianza: "media_baja",
        alias: ["E621", "MSG"],
      },
      glutamatos: {
        nombre: "Glutamatos",
        tipo: "potenciador",
        estado: "mezcla",
        histamina: 1,
        confianza: "media_baja",
        alias: ["E620", "E621", "E622", "E623", "E624", "E625"],
      },

      nitritos_nitratos: {
        nombre: "Nitritos y nitratos",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E249", "E250", "E251", "E252"],
      },
      nitrito_potasico: {
        nombre: "Nitrito potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E249"],
      },
      nitrito_sodico: {
        nombre: "Nitrito sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E250"],
      },
      nitrato_sodico: {
        nombre: "Nitrato sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E251"],
      },
      nitrato_potasico: {
        nombre: "Nitrato potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E252"],
      },

      sorbatos: {
        nombre: "Sorbatos",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E200", "E202", "E203"],
      },
      acido_sorbico: {
        nombre: "Ácido sórbico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E200"],
      },
      sorbato_potasico: {
        nombre: "Sorbato potásico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 1,
        confianza: "baja",
        alias: ["E202"],
      },

      acido_ascorbico: {
        nombre: "Ácido ascórbico",
        tipo: "antioxidante",
        estado: "procesado",
        histamina: 0,
        confianza: "alta",
        alias: ["E300", "Vitamina C"],
      },
      ascorbato_sodico: {
        nombre: "Ascorbato sódico",
        tipo: "antioxidante",
        estado: "procesado",
        histamina: 0,
        confianza: "alta",
        alias: ["E301"],
      },
      ascorbato_calcico: {
        nombre: "Ascorbato cálcico",
        tipo: "antioxidante",
        estado: "procesado",
        histamina: 0,
        confianza: "alta",
        alias: ["E302"],
      },

      propionatos: {
        nombre: "Propionatos",
        tipo: "conservante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E280", "E281", "E282", "E283"],
      },
      acido_propionico: {
        nombre: "Ácido propiónico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E280"],
      },
      propionato_sodico: {
        nombre: "Propionato sódico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E281"],
      },
      propionato_calcico: {
        nombre: "Propionato cálcico",
        tipo: "conservante",
        estado: "procesado",
        histamina: 0,
        confianza: "media",
        alias: ["E282"],
      },

      edta_calcico_disodico: {
        nombre: "EDTA cálcico disódico",
        tipo: "secuestrante",
        estado: "procesado",
        histamina: 0,
        confianza: "baja",
        alias: ["E385"],
      },
    },
  },
};
